name: build our image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: check out path
        uses: actions/checkout@v2

      - name: testing
        run: go test ./...

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build image
        run: |
          docker buildx build \
            --push \
            --tag xiao4011/toolbox:latest \
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6  .

  deploy:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/docker-deployment
      - name: Deploy to Docker
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ${{ secrets.SERVER_HOST }}
          remote_docker_port: ${{ secrets.SERVER_PORT }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: false
          deploy_path: /home/pi/svc/toolbox
          stack_file_name: docker-compose.yml
          keep_files: 3
          pull_images_first: true
          args: --project-name toolbox up -d
