name: build our image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: check out path
        uses: actions/checkout@v2

      - name: testing
        run: go test ./...

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build image
        run: |
          docker buildx build \
            --push \
            --tag xiaoxiaosn/toolbox:latest \
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6  .

